#!/usr/bin/python2.6
# -*- coding: utf8 -*-

"""
pul_cancel: Cancel one or several jobs according to the given filters.

This utility is a wrapper on the more flexible "pul_set_status" utility.
Will set the status of jobs to DONE on the server according to the specified constraints
"""
__author__      = "Jérôme Samson"
__copyright__   = "Copyright 2013, Mikros Image"

import os
import sys

###########################################################################################################################
if __name__ == '__main__':

	argString = ''
	for i in range(1, len(sys.argv)):
		argString += " %s" % sys.argv[i]

	command = "./pul_set_status --set 5 %s" % argString
	os.system(command)