#!/bin/bash
export PYTHONPATH=/s/apps/lin/puli/:${PYTHONPATH}
export PATH=/s/apps/lin/puli/tools/stats:${PATH}

cd /s/apps/lin/puli/tools/stats
/s/apps/lin/puli/tools/stats/grab_usage_stats "$@"
cd -
