#!/bin/bash

# DEV env
#export PYTHONPATH=/datas/jsa/OpenRenderManagement/Puli/src:${PYTHONPATH}
# BASEDIR="/datas/jsa/OpenRenderManagement/Puli/src/tools/stats"

# PROD env
export PYTHONPATH=/s/apps/lin/puli/:${PYTHONPATH}
BASEDIR="/s/apps/lin/puli/pulitools/stats"

python ${BASEDIR}/grab_queue_stats.py "$@"
