#!/bin/bash
#export PYTHONPATH=/s/apps/lin/puli/:${PYTHONPATH}
#export PATH=/s/apps/lin/puli/tools/puliquery:${PATH}

cd /s/apps/lin/vfx_test_apps/OpenRenderManagement/Puli/src/tools/statsviewer
python stats.py
cd - > /dev/null