#!/bin/bash
export PYTHONPATH=/s/apps/lin/puli/:${PYTHONPATH}
export PATH=/s/apps/lin/puli/tools/puliquery:${PATH}

cd /s/apps/lin/puli/tools/puliquery
/s/apps/lin/puli/tools/puliquery/pul_set_pause --set 0 "$@"
cd -
