#!/bin/bash
# export PYTHONPATH=/s/apps/lin/puli/:${PYTHONPATH}
# export PYTHONPATH=/datas/jsa/OpenRenderManagement/Puli/src:${PYTHONPATH}
# export PATH=/s/apps/lin/puli/tools/stats:${PATH}

#cd /s/apps/lin/puli/tools/stats
# cd /datas/jsa/OpenRenderManagement/Puli/src/tools/stats/
# python ./display_renderfarm_usage.py "$@"
# cd - > /dev/null


export PYTHONPATH=/s/apps/lin/vfx_test_apps/OpenRenderManagement/Puli/src/:${PYTHONPATH}
export PATH=/s/apps/lin/vfx_test_apps/OpenRenderManagement/Puli/src/tools/stats:${PATH}

python /s/apps/lin/vfx_test_apps/OpenRenderManagement/Puli/src/tools/stats/display_renderfarm_usage.py "$@"
