#!/bin/bash
#export PYTHONPATH=/s/apps/lin/puli/:${PYTHONPATH}
export PYTHONPATH=/datas/jsa/OpenRenderManagement/Puli/src:${PYTHONPATH}
export PATH=/s/apps/lin/puli/pulitools/stats:${PATH}

# python /datas/jsa/OpenRenderManagement/Puli/src/tools/stats/display_2dim_usage.py -f /s/apps/lin/vfx_test_apps/OpenRenderManagement/stats/FR/logs/queue_stats.log -o /s/apps/lin/vfx_test_apps/OpenRenderManagement/stats/FR/graphs/rn_by_prod_avg_24.svg -s 24 -r 30 -t "Allocated RN by prod over time" prod allocatedRN
python /datas/jsa/OpenRenderManagement/Puli/src/pulitools/stats/display_queue_usage.py -f /s/apps/lin/vfx_test_apps/OpenRenderManagement/stats/FR/logs/queue_stats.log -o /s/apps/lin/vfx_test_apps/OpenRenderManagement/stats/FR/graphs/queue_avg_24.svg -s 24 -r 30 --stack -t "Jobs by status over time"