# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsrc/mainwindow.ui'
#
# Created: Mon Apr  7 11:24:59 2014
#      by: PyQt4 UI code generator 4.6.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 583)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, -1, 791, 125))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lblEndDate = QtGui.QLabel(self.gridLayoutWidget)
        self.lblEndDate.setObjectName("lblEndDate")
        self.gridLayout.addWidget(self.lblEndDate, 3, 1, 1, 1)
        self.lblStartDate = QtGui.QLabel(self.gridLayoutWidget)
        self.lblStartDate.setObjectName("lblStartDate")
        self.gridLayout.addWidget(self.lblStartDate, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 13, 1, 1)
        self.lblSelectReport = QtGui.QLabel(self.gridLayoutWidget)
        self.lblSelectReport.setObjectName("lblSelectReport")
        self.gridLayout.addWidget(self.lblSelectReport, 1, 1, 1, 1)
        self.dtStartDate = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        self.dtStartDate.setObjectName("dtStartDate")
        self.gridLayout.addWidget(self.dtStartDate, 2, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 1, 1, 1)
        self.dtEndDate = QtGui.QDateTimeEdit(self.gridLayoutWidget)
        self.dtEndDate.setObjectName("dtEndDate")
        self.gridLayout.addWidget(self.dtEndDate, 3, 3, 1, 1)
        self.chkIdle = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkIdle.setChecked(True)
        self.chkIdle.setObjectName("chkIdle")
        self.gridLayout.addWidget(self.chkIdle, 5, 13, 1, 1)
        self.chkPaused = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkPaused.setChecked(True)
        self.chkPaused.setObjectName("chkPaused")
        self.gridLayout.addWidget(self.chkPaused, 5, 12, 1, 1)
        self.chkWorking = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkWorking.setChecked(True)
        self.chkWorking.setObjectName("chkWorking")
        self.gridLayout.addWidget(self.chkWorking, 5, 11, 1, 1)
        self.chkOffline = QtGui.QCheckBox(self.gridLayoutWidget)
        self.chkOffline.setChecked(True)
        self.chkOffline.setObjectName("chkOffline")
        self.gridLayout.addWidget(self.chkOffline, 5, 4, 1, 1)
        self.btnRefresh = QtGui.QPushButton(self.gridLayoutWidget)
        self.btnRefresh.setObjectName("btnRefresh")
        self.gridLayout.addWidget(self.btnRefresh, 5, 3, 1, 1)
        self.cbReport = QtGui.QComboBox(self.gridLayoutWidget)
        self.cbReport.setObjectName("cbReport")
        self.gridLayout.addWidget(self.cbReport, 1, 3, 1, 1)
        self.frame = QtGui.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(9, 129, 791, 391))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.webView = QtWebKit.QWebView(self.frame)
        self.webView.setGeometry(QtCore.QRect(9, 9, 771, 371))
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 814, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lblEndDate.setText(QtGui.QApplication.translate("MainWindow", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStartDate.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectReport.setText(QtGui.QApplication.translate("MainWindow", "Select report", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIdle.setText(QtGui.QApplication.translate("MainWindow", "Idle", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPaused.setText(QtGui.QApplication.translate("MainWindow", "Paused", None, QtGui.QApplication.UnicodeUTF8))
        self.chkWorking.setText(QtGui.QApplication.translate("MainWindow", "Working", None, QtGui.QApplication.UnicodeUTF8))
        self.chkOffline.setText(QtGui.QApplication.translate("MainWindow", "Offline", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRefresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
