# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsrc/ui/mainwindow.ui'
#
# Created: Tue May  6 19:08:29 2014
#      by: PyQt4 UI code generator 4.6.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 747)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterLayout = QtGui.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.dataFilterLayout = QtGui.QFormLayout()
        self.dataFilterLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.dataFilterLayout.setObjectName("dataFilterLayout")
        self.lblSelectAReport = QtGui.QLabel(self.centralwidget)
        self.lblSelectAReport.setObjectName("lblSelectAReport")
        self.dataFilterLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblSelectAReport)
        self.cbReport = QtGui.QComboBox(self.centralwidget)
        self.cbReport.setEnabled(True)
        self.cbReport.setObjectName("cbReport")
        self.dataFilterLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbReport)
        self.displayNHoursLabel = QtGui.QLabel(self.centralwidget)
        self.displayNHoursLabel.setObjectName("displayNHoursLabel")
        self.dataFilterLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.displayNHoursLabel)
        self.lenghtLayout = QtGui.QHBoxLayout()
        self.lenghtLayout.setObjectName("lenghtLayout")
        self.slLength = QtGui.QSlider(self.centralwidget)
        self.slLength.setMinimum(1)
        self.slLength.setMaximum(168)
        self.slLength.setProperty("value", 24)
        self.slLength.setOrientation(QtCore.Qt.Horizontal)
        self.slLength.setObjectName("slLength")
        self.lenghtLayout.addWidget(self.slLength)
        self.spLength = QtGui.QSpinBox(self.centralwidget)
        self.spLength.setMinimum(1)
        self.spLength.setMaximum(168)
        self.spLength.setSingleStep(1)
        self.spLength.setProperty("value", 24)
        self.spLength.setObjectName("spLength")
        self.lenghtLayout.addWidget(self.spLength)
        self.dataFilterLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.lenghtLayout)
        self.lblUntil = QtGui.QLabel(self.centralwidget)
        self.lblUntil.setObjectName("lblUntil")
        self.dataFilterLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblUntil)
        self.endLayout = QtGui.QHBoxLayout()
        self.endLayout.setObjectName("endLayout")
        self.chkNow = QtGui.QCheckBox(self.centralwidget)
        self.chkNow.setChecked(True)
        self.chkNow.setObjectName("chkNow")
        self.endLayout.addWidget(self.chkNow)
        self.dtEndDate = QtGui.QDateTimeEdit(self.centralwidget)
        self.dtEndDate.setEnabled(False)
        self.dtEndDate.setObjectName("dtEndDate")
        self.endLayout.addWidget(self.dtEndDate)
        self.dataFilterLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.endLayout)
        self.filterLayout.addLayout(self.dataFilterLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.filterLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.filterLayout)
        self.optionsLayout = QtGui.QHBoxLayout()
        self.optionsLayout.setObjectName("optionsLayout")
        self.reportGroupBox = QtGui.QVBoxLayout()
        self.reportGroupBox.setObjectName("reportGroupBox")
        self.gbJobUsage = QtGui.QGroupBox(self.centralwidget)
        self.gbJobUsage.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gbJobUsage.setObjectName("gbJobUsage")
        self.formLayout = QtGui.QFormLayout(self.gbJobUsage)
        self.formLayout.setObjectName("formLayout")
        self.cbTrack = QtGui.QComboBox(self.gbJobUsage)
        self.cbTrack.setObjectName("cbTrack")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cbTrack)
        self.label = QtGui.QLabel(self.gbJobUsage)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.groupByLabel = QtGui.QLabel(self.gbJobUsage)
        self.groupByLabel.setObjectName("groupByLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.groupByLabel)
        self.cbGroupBy = QtGui.QComboBox(self.gbJobUsage)
        self.cbGroupBy.setObjectName("cbGroupBy")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbGroupBy)
        self.reportGroupBox.addWidget(self.gbJobUsage)
        self.gbRnUsage = QtGui.QGroupBox(self.centralwidget)
        self.gbRnUsage.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gbRnUsage.setFlat(False)
        self.gbRnUsage.setObjectName("gbRnUsage")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.gbRnUsage)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.chkWorking = QtGui.QCheckBox(self.gbRnUsage)
        self.chkWorking.setChecked(True)
        self.chkWorking.setObjectName("chkWorking")
        self.horizontalLayout_12.addWidget(self.chkWorking)
        self.chkPaused = QtGui.QCheckBox(self.gbRnUsage)
        self.chkPaused.setChecked(True)
        self.chkPaused.setObjectName("chkPaused")
        self.horizontalLayout_12.addWidget(self.chkPaused)
        self.chkIdle = QtGui.QCheckBox(self.gbRnUsage)
        self.chkIdle.setChecked(True)
        self.chkIdle.setObjectName("chkIdle")
        self.horizontalLayout_12.addWidget(self.chkIdle)
        self.chkOffline = QtGui.QCheckBox(self.gbRnUsage)
        self.chkOffline.setChecked(True)
        self.chkOffline.setObjectName("chkOffline")
        self.horizontalLayout_12.addWidget(self.chkOffline)
        self.reportGroupBox.addWidget(self.gbRnUsage)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.reportGroupBox.addItem(spacerItem1)
        self.optionsLayout.addLayout(self.reportGroupBox)
        self.displayGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.displayGroupBox.setMaximumSize(QtCore.QSize(269, 16777215))
        self.displayGroupBox.setObjectName("displayGroupBox")
        self.formLayout_4 = QtGui.QFormLayout(self.displayGroupBox)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lblResolution = QtGui.QLabel(self.displayGroupBox)
        self.lblResolution.setObjectName("lblResolution")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblResolution)
        self.resolutionLayout = QtGui.QHBoxLayout()
        self.resolutionLayout.setObjectName("resolutionLayout")
        self.slResolution = QtGui.QSlider(self.displayGroupBox)
        self.slResolution.setMinimum(8)
        self.slResolution.setMaximum(60)
        self.slResolution.setSingleStep(1)
        self.slResolution.setProperty("value", 30)
        self.slResolution.setOrientation(QtCore.Qt.Horizontal)
        self.slResolution.setObjectName("slResolution")
        self.resolutionLayout.addWidget(self.slResolution)
        self.spResolution = QtGui.QSpinBox(self.displayGroupBox)
        self.spResolution.setMinimum(8)
        self.spResolution.setMaximum(60)
        self.spResolution.setSingleStep(1)
        self.spResolution.setProperty("value", 30)
        self.spResolution.setObjectName("spResolution")
        self.resolutionLayout.addWidget(self.spResolution)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.resolutionLayout)
        self.lblGraphType = QtGui.QLabel(self.displayGroupBox)
        self.lblGraphType.setObjectName("lblGraphType")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblGraphType)
        self.cbGraphType = QtGui.QComboBox(self.displayGroupBox)
        self.cbGraphType.setObjectName("cbGraphType")
        self.cbGraphType.addItem("")
        self.cbGraphType.addItem("")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.cbGraphType)
        self.lblScaleType = QtGui.QLabel(self.displayGroupBox)
        self.lblScaleType.setObjectName("lblScaleType")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblScaleType)
        self.cbScaleType = QtGui.QComboBox(self.displayGroupBox)
        self.cbScaleType.setObjectName("cbScaleType")
        self.cbScaleType.addItem("")
        self.cbScaleType.addItem("")
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.cbScaleType)
        self.lblStyle = QtGui.QLabel(self.displayGroupBox)
        self.lblStyle.setObjectName("lblStyle")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.lblStyle)
        self.cbGraphStyle = QtGui.QComboBox(self.displayGroupBox)
        self.cbGraphStyle.setObjectName("cbGraphStyle")
        self.cbGraphStyle.addItem("")
        self.cbGraphStyle.addItem("")
        self.cbGraphStyle.addItem("")
        self.cbGraphStyle.addItem("")
        self.cbGraphStyle.addItem("")
        self.cbGraphStyle.addItem("")
        self.cbGraphStyle.addItem("")
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbGraphStyle)
        self.lblScaleRound = QtGui.QLabel(self.displayGroupBox)
        self.lblScaleRound.setObjectName("lblScaleRound")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.lblScaleRound)
        self.cbScaleRound = QtGui.QComboBox(self.displayGroupBox)
        self.cbScaleRound.setObjectName("cbScaleRound")
        self.cbScaleRound.addItem("")
        self.cbScaleRound.addItem("")
        self.cbScaleRound.addItem("")
        self.cbScaleRound.addItem("")
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.cbScaleRound)
        self.spScaleResolution = QtGui.QSpinBox(self.displayGroupBox)
        self.spScaleResolution.setMinimum(8)
        self.spScaleResolution.setMaximum(40)
        self.spScaleResolution.setProperty("value", 20)
        self.spScaleResolution.setObjectName("spScaleResolution")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.FieldRole, self.spScaleResolution)
        self.lblScaleResolution = QtGui.QLabel(self.displayGroupBox)
        self.lblScaleResolution.setObjectName("lblScaleResolution")
        self.formLayout_4.setWidget(5, QtGui.QFormLayout.LabelRole, self.lblScaleResolution)
        self.optionsLayout.addWidget(self.displayGroupBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.optionsLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.optionsLayout)
        self.webView = QtWebKit.QWebView(self.centralwidget)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout.addWidget(self.webView)
        self.log = QtGui.QPlainTextEdit(self.centralwidget)
        self.log.setMaximumSize(QtCore.QSize(16777215, 60))
        self.log.setUndoRedoEnabled(False)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.verticalLayout.addWidget(self.log)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 843, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setEnabled(False)
        self.menuFile.setObjectName("menuFile")
        self.menuSnapshots = QtGui.QMenu(self.menubar)
        self.menuSnapshots.setEnabled(False)
        self.menuSnapshots.setObjectName("menuSnapshots")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(24, 24))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSnapshot = QtGui.QAction(MainWindow)
        self.actionSnapshot.setObjectName("actionSnapshot")
        self.actionCreate = QtGui.QAction(MainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionClear_all_snapshots = QtGui.QAction(MainWindow)
        self.actionClear_all_snapshots.setObjectName("actionClear_all_snapshots")
        self.actionGenerate = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGenerate.setIcon(icon)
        self.actionGenerate.setIconVisibleInMenu(True)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionReset = QtGui.QAction(MainWindow)
        self.actionReset.setEnabled(True)
        self.actionReset.setObjectName("actionReset")
        self.actionExport_as = QtGui.QAction(MainWindow)
        self.actionExport_as.setObjectName("actionExport_as")
        self.menuFile.addAction(self.actionExport_as)
        self.menuSnapshots.addAction(self.actionCreate)
        self.menuSnapshots.addAction(self.actionDelete)
        self.menuSnapshots.addAction(self.actionClear_all_snapshots)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSnapshots.menuAction())
        self.toolBar.addAction(self.actionGenerate)
        self.toolBar.addAction(self.actionReset)

        self.retranslateUi(MainWindow)
        self.cbScaleRound.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Stats Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectAReport.setText(QtGui.QApplication.translate("MainWindow", "Select a report", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNHoursLabel.setText(QtGui.QApplication.translate("MainWindow", "Display N hours", None, QtGui.QApplication.UnicodeUTF8))
        self.lblUntil.setText(QtGui.QApplication.translate("MainWindow", "Until", None, QtGui.QApplication.UnicodeUTF8))
        self.chkNow.setText(QtGui.QApplication.translate("MainWindow", "Now", None, QtGui.QApplication.UnicodeUTF8))
        self.gbJobUsage.setTitle(QtGui.QApplication.translate("MainWindow", "Jobs usage options", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Track Value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupByLabel.setText(QtGui.QApplication.translate("MainWindow", "Group by", None, QtGui.QApplication.UnicodeUTF8))
        self.gbRnUsage.setTitle(QtGui.QApplication.translate("MainWindow", "RN usage options", None, QtGui.QApplication.UnicodeUTF8))
        self.chkWorking.setText(QtGui.QApplication.translate("MainWindow", "Working", None, QtGui.QApplication.UnicodeUTF8))
        self.chkPaused.setText(QtGui.QApplication.translate("MainWindow", "Paused", None, QtGui.QApplication.UnicodeUTF8))
        self.chkIdle.setText(QtGui.QApplication.translate("MainWindow", "Idle", None, QtGui.QApplication.UnicodeUTF8))
        self.chkOffline.setText(QtGui.QApplication.translate("MainWindow", "Offline", None, QtGui.QApplication.UnicodeUTF8))
        self.displayGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Display options", None, QtGui.QApplication.UnicodeUTF8))
        self.lblResolution.setText(QtGui.QApplication.translate("MainWindow", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.lblGraphType.setText(QtGui.QApplication.translate("MainWindow", "Graph type", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGraphType.setItemText(0, QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGraphType.setItemText(1, QtGui.QApplication.translate("MainWindow", "Stacked", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScaleType.setText(QtGui.QApplication.translate("MainWindow", "Scale type", None, QtGui.QApplication.UnicodeUTF8))
        self.cbScaleType.setItemText(0, QtGui.QApplication.translate("MainWindow", "Standard", None, QtGui.QApplication.UnicodeUTF8))
        self.cbScaleType.setItemText(1, QtGui.QApplication.translate("MainWindow", "Logarithmic", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStyle.setText(QtGui.QApplication.translate("MainWindow", "Style", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGraphStyle.setItemText(0, QtGui.QApplication.translate("MainWindow", "RedBlue", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGraphStyle.setItemText(1, QtGui.QApplication.translate("MainWindow", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGraphStyle.setItemText(2, QtGui.QApplication.translate("MainWindow", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGraphStyle.setItemText(3, QtGui.QApplication.translate("MainWindow", "Light", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGraphStyle.setItemText(4, QtGui.QApplication.translate("MainWindow", "Clean", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGraphStyle.setItemText(5, QtGui.QApplication.translate("MainWindow", "DarkColorized", None, QtGui.QApplication.UnicodeUTF8))
        self.cbGraphStyle.setItemText(6, QtGui.QApplication.translate("MainWindow", "DarkGreenBlue", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScaleRound.setText(QtGui.QApplication.translate("MainWindow", "Round time (min)", None, QtGui.QApplication.UnicodeUTF8))
        self.cbScaleRound.setItemText(0, QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cbScaleRound.setItemText(1, QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.cbScaleRound.setItemText(2, QtGui.QApplication.translate("MainWindow", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.cbScaleRound.setItemText(3, QtGui.QApplication.translate("MainWindow", "60", None, QtGui.QApplication.UnicodeUTF8))
        self.lblScaleResolution.setText(QtGui.QApplication.translate("MainWindow", "Resolution in scale", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "&Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSnapshots.setTitle(QtGui.QApplication.translate("MainWindow", "&Snapshots", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSnapshot.setText(QtGui.QApplication.translate("MainWindow", "Snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate.setText(QtGui.QApplication.translate("MainWindow", "&Create", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCreate.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_all_snapshots.setText(QtGui.QApplication.translate("MainWindow", "Clear all snapshots", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate.setToolTip(QtGui.QApplication.translate("MainWindow", "Create graph with current parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate.setStatusTip(QtGui.QApplication.translate("MainWindow", "Create graph with current parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerate.setShortcut(QtGui.QApplication.translate("MainWindow", "F5", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setToolTip(QtGui.QApplication.translate("MainWindow", "Set parameter values to default", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_as.setText(QtGui.QApplication.translate("MainWindow", "&Export to...", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
